"""Add user_id to chat

Revision ID: 6dcaacdf6942
Revises: d6c83092771a
Create Date: 2025-11-15 15:24:21.493885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6dcaacdf6942"
down_revision: Union[str, Sequence[str], None] = "d6c83092771a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_chats_user_id_users"), "chats", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_chats_user_id_users"), "chats", type_="foreignkey")
    op.drop_column("chats", "user_id")
    # ### end Alembic commands ###
